data:
  train_files: mlfoundations/clicks-100k@train
  val_files: mlfoundations/clicks-100k@train
  prompt_key: easyr1_prompt
  answer_key: normalized_bbox
  image_key: images
  image_dir: null
  max_prompt_length: 5200
  max_response_length: 16
  rollout_batch_size: 128  # equivalent to verl's data.train_batch_size
  mini_rollout_batch_size: 512  # equivalent to verl's data.gen_batch_size
  val_batch_size: 512
  format_prompt: ./examples/format_prompt/gui.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  min_pixels: 1000
  max_pixels: 4000000
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: true
  use_kl_loss: false
  kl_penalty: low_var_kl
  kl_coef: 0.0
  online_filtering: true
  filter_low: 0.01
  filter_high: 0.49

worker:
  actor:
    global_batch_size: 128  # equivalent to verl's actor.ppo_mini_batch_size
    micro_batch_size_per_device_for_update: 1  # equivalent to verl's actor.ppo_micro_batch_size_per_gpu
    micro_batch_size_per_device_for_experience: 1  # equivalent to verl's rollout.log_prob_micro_batch_size_per_gpu
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    clip_ratio_low: 0.2
    clip_ratio_high: 0.28
    model:
      model_path: Qwen/Qwen3-VL-30B-A3B-Instruct
      tokenizer_path: Qwen/Qwen3-VL-30B-A3B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
      
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw_bf16  # {adamw, adamw_bf16}
      lr_warmup_ratio: 0.0
    fsdp:
      torch_dtype: bf16
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true  # true: more CPU memory; false: more GPU memory
      offload_optimizer: true  # true: more CPU memory; false: more GPU memory

  rollout:
    n: 8
    temperature: 1.0
    top_p: 1.0
    limit_images: 0
    dtype: bfloat16
    max_num_batched_tokens: 8096
    gpu_memory_utilization: 0.7
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 16
    disable_tqdm: false
    val_override_config:
      temperature: 0.0
      top_p: 1.0
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false  # true: more CPU memory; false: more GPU memory
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: sequential
    reward_function: ./examples/reward_function/norm_gui_reward.py:compute_score

trainer:
  total_epochs: 1
  max_steps: null
  project_name: easy_r1
  experiment_name: gelato_30b
  logger: ["tensorboard"]
  nnodes: 8
  n_gpus_per_node: 4
  max_try_make_batch: -1  # -1 means no limit
  val_freq: -1  # -1 to disable
  val_before_train: false
  val_only: false
  val_generations_to_log: 5
  save_freq: 3  # -1 to disable
  save_limit: -1  # -1 to disable
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
  find_last_checkpoint: true
